# Generated by Django 4.1.10 on 2023-08-26 11:54

from django.db import migrations


def create_users(apps, schema_editor):
    from django.contrib.auth.models import User
    User.objects.create_user('user1', 'user1@next-level-agency.ru', 'password')
    User.objects.create_user('test', 'test@test.org', 'test')


def delete_users(apps, schema_editor):
    from django.contrib.auth.models import User
    User.objects.get(username='user1').delete()
    User.objects.get(username='test').delete()


def create_contacts(apps, schema_editor):
    from ..models import Contact
    first_names = ('Иван', 'Игорь', 'Сергей', 'Алексей', 'Олег')
    last_names = ('Осипов', 'Николаев', 'Иванов', 'Романов', 'Кузнецов', 'Смирнов', 'Петров')
    email_start = ('tech', 'support', 'helpdesk', 'hr', 'recruitment', 'staff', 'management')
    email_finish = ('yandex.ru', 'mail.ru', 'vk.com', 'tinkoff.ru', 'sber.ru')
    Contact.objects.bulk_create(
        [Contact(first_name=first_names[i % len(first_names)],
                 last_name=last_names[i % len(last_names)],
                 phone_number=f'+793{i % 7}{i % 3}831{i % 5}54',
                 email=f'{email_start[i % len(email_start)]}@{email_finish[i % len(email_finish)]}')
         for i in range(20)]
    )

def delete_contacts(apps, schema_editor):
    from ..models import Contact
    Contact.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_users, delete_users),
        migrations.RunPython(create_contacts, delete_contacts),
    ]
